import yaml from 'js-yaml';

const WELL_KNOWN_PLACEHOLDERS = {
  userId: 'test-user-123',
  email: 'user@example.com',
  login: 'user@example.com',
  firstName: 'Test',
  lastName: 'User',
  domain: 'dev-123.example.com',
  subject: 'test-subject',
  audience: 'https://audience.example.com',
  groupId: 'test-group-123',
  groupIds: 'group-1,group-2',
  roleId: 'test-role-123',
  accountId: 'test-account-123',
  sessionId: 'test-session-123',
  permissionSetId: 'test-permission-set-123',
  channel: 'test-channel',
  message: 'Test message'
};

const TYPE_DEFAULTS = {
  text: (name) => `test-${name}`,
  number: () => 42,
  boolean: () => true
};

/**
 * Return a sensible placeholder value for a metadata input field.
 *
 * @param {string} name  - Input field name (e.g. "userId")
 * @param {string} type  - Input type from metadata (e.g. "text", "number", "boolean")
 * @returns {string|number|boolean}
 */
export function inputPlaceholder(name, type) {
  if (WELL_KNOWN_PLACEHOLDERS[name] !== undefined) {
    return WELL_KNOWN_PLACEHOLDERS[name];
  }
  const factory = TYPE_DEFAULTS[type] ?? TYPE_DEFAULTS.text;
  return factory(name);
}

const AUTH_PRESETS = {
  bearer: {
    secrets: { BEARER_AUTH_TOKEN: 'test-token-123' },
    environment: {},
    crypto: { signJWT: { returns: 'mock.jwt.token' } }
  },
  basic: {
    secrets: { BASIC_USERNAME: 'test-access-key', BASIC_PASSWORD: 'test-secret-key' },
    environment: {},
    crypto: null
  },
  oauth2_authorization_code: {
    secrets: { OAUTH2_AUTHORIZATION_CODE_ACCESS_TOKEN: 'test-access-token' },
    environment: {},
    crypto: null
  },
  oauth2_client_credentials: {
    secrets: { OAUTH2_CLIENT_CREDENTIALS_CLIENT_SECRET: 'test-client-secret' },
    environment: {
      OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL: 'https://example.com/oauth/token',
      OAUTH2_CLIENT_CREDENTIALS_CLIENT_ID: 'test-client-id',
      OAUTH2_CLIENT_CREDENTIALS_SCOPE: '',
      OAUTH2_CLIENT_CREDENTIALS_AUDIENCE: '',
      OAUTH2_CLIENT_CREDENTIALS_AUTH_STYLE: 'InHeader'
    },
    crypto: null
  },
  none: {
    secrets: {},
    environment: {},
    crypto: null
  }
};

/**
 * Generate a scenarios.yaml string from parsed metadata.
 *
 * @param {{ name: string, inputs: Object }} metadata
 * @param {{ auth?: string }} [options]
 * @returns {string} YAML content with TODO comments
 */
export function generateScenariosYaml(metadata, options = {}) {
  const authType = options.auth || 'bearer';
  const preset = AUTH_PRESETS[authType];
  if (!preset) {
    throw new Error(`Unknown auth type "${authType}". Valid types: ${Object.keys(AUTH_PRESETS).join(', ')}`);
  }

  const params = {};
  for (const [name, def] of Object.entries(metadata.inputs ?? {})) {
    params[name] = inputPlaceholder(name, def.type);
  }

  const context = {
    secrets: preset.secrets,
    environment: preset.environment || {}
  };
  if (preset.crypto) {
    context.crypto = preset.crypto;
  }

  const doc = {
    action: {
      params,
      context
    },
    scenarios: [
      {
        name: 'TODO: describe the success case',
        record: true
      }
    ]
  };

  const rawYaml = yaml.dump(doc, {
    lineWidth: -1,
    quotingType: '"',
    forceQuotes: false,
    noRefs: true
  });

  const comments = [
    '# Generated by sgnl-test-init — fill in the TODOs below',
    '#',
    '# Scenarios with "record: true" will be recorded by: npx sgnl-test-record',
    '# Fill in real secrets in action.context.secrets, then run the recorder.',
    '# After recording, redact secrets before committing.',
    ''
  ].join('\n');

  return comments + rawYaml;
}
