import yaml from 'js-yaml';

const WELL_KNOWN_PLACEHOLDERS = {
  userId: 'test-user-123',
  email: 'user@example.com',
  login: 'user@example.com',
  firstName: 'Test',
  lastName: 'User',
  domain: 'dev-123.example.com',
  subject: 'test-subject',
  audience: 'https://audience.example.com',
  groupId: 'test-group-123',
  groupIds: 'group-1,group-2',
  roleId: 'test-role-123',
  accountId: 'test-account-123',
  sessionId: 'test-session-123',
  permissionSetId: 'test-permission-set-123',
  channel: 'test-channel',
  message: 'Test message'
};

const TYPE_DEFAULTS = {
  text: (name) => `test-${name}`,
  number: () => 42,
  boolean: () => true
};

/**
 * Return a sensible placeholder value for a metadata input field.
 *
 * @param {string} name  - Input field name (e.g. "userId")
 * @param {string} type  - Input type from metadata (e.g. "text", "number", "boolean")
 * @returns {string|number|boolean}
 */
export function inputPlaceholder(name, type) {
  if (WELL_KNOWN_PLACEHOLDERS[name] !== undefined) {
    return WELL_KNOWN_PLACEHOLDERS[name];
  }
  const factory = TYPE_DEFAULTS[type] ?? TYPE_DEFAULTS.text;
  return factory(name);
}

/**
 * Generate a boilerplate HTTP fixture file for a 200 success response.
 *
 * @returns {string} Raw HTTP response content
 */
export function generateFixture() {
  return [
    'HTTP/1.1 200 OK',
    'Content-Type: application/json',
    '',
    '{"TODO": "replace with actual API response body"}',
    ''
  ].join('\n');
}

/**
 * Generate a scenarios.yaml string from parsed metadata.
 *
 * @param {{ name: string, inputs: Object }} metadata
 * @returns {string} YAML content with TODO comments
 */
export function generateScenariosYaml(metadata) {
  const params = {};
  for (const [name, def] of Object.entries(metadata.inputs ?? {})) {
    if (name === 'address') continue;
    params[name] = inputPlaceholder(name, def.type);
  }

  const doc = {
    action: {
      params,
      context: {
        secrets: {
          BEARER_AUTH_TOKEN: 'test-token-123'
        },
        environment: {
          ADDRESS: 'https://api.example.com'
        }
      }
    },
    scenarios: [
      {
        name: 'TODO: describe the success case',
        request: {
          method: 'POST',
          url: 'https://api.example.com/TODO/your/endpoint'
        },
        fixture: 'fixtures/200-success.http',
        invoke: {
          returns: {
            status: 'success'
          }
        }
      }
    ]
  };

  const rawYaml = yaml.dump(doc, {
    lineWidth: -1,
    quotingType: '"',
    forceQuotes: false,
    noRefs: true
  });

  const comments = [
    '# Generated by sgnl-test-init — fill in the TODOs below',
    '#',
    '# TODO: Update the request method and URL to match your action\'s API call',
    '# TODO: Update invoke.returns to match your action\'s actual return values',
    '# TODO: Add more scenarios for error cases (429, 401, etc.)',
    ''
  ].join('\n');

  return comments + rawYaml;
}
